apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: okondrashin/microservices-demo-frontend:v0.0.2
          env:
            - name: "PRODUCT_CATALOG_SERVICE_ADDR"
              value: "undefined"
            - name: "CURRENCY_SERVICE_ADDR"
              value: "undefined"
            - name: "CART_SERVICE_ADDR"
              value: "undefined"
            - name: "RECOMMENDATION_SERVICE_ADDR"
              value: "undefined"
            - name: "CHECKOUT_SERVICE_ADDR"
              value: "undefined"
            - name: "SHIPPING_SERVICE_ADDR"
              value: "undefined"
            - name: "AD_SERVICE_ADDR"
              value: "undefined"