apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: okondrashin/microservices-demo-frontend
    name: frontend
    resources: {}
    env:
      - name: "PRODUCT_CATALOG_SERVICE_ADDR"
        value: "undefined"
      - name: "CURRENCY_SERVICE_ADDR"
        value: "undefined"
      - name: "CART_SERVICE_ADDR"
        value: "undefined"
      - name: "RECOMMENDATION_SERVICE_ADDR"
        value: "undefined"
      - name: "CHECKOUT_SERVICE_ADDR"
        value: "undefined"
      - name: "SHIPPING_SERVICE_ADDR"
        value: "undefined"
      - name: "AD_SERVICE_ADDR"
        value: "undefined"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}