apiVersion: v1
kind: Pod
metadata:
  name: "web"
spec:
  containers:
    - name: "web"
      image: "okondrashin/kubernetes-intro-web"
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: "web-init"
      image: "busybox:1.31.0"
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}